### ISSUE TITLE
Container linux specific options

### ISSUE THREAD

**Issue by dirkjonker** [terraform-providers/terraform-provider-ignition#22]
Is it possible to use this provider to set CoreOS etcd and locksmith settings? E.g. to implement the extra specification from https://coreos.com/os/docs/latest/configuration.html
The yaml version of what one might want to configure:

```yaml
etcd:
  version:                     "3.0.15"
  name:                        "{HOSTNAME}"
  advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{PRIVATE_IPV4}:2380"
  initial_cluster:             "{HOSTNAME}=http://{PRIVATE_IPV4}:2380"
update:
  group:  "beta"
locksmith:
  reboot_strategy: "etcd-lock"
  window_start:    "Sun 1:00"
  window_length:   "2h"
```
(examples are from [CoreOS docs](https://coreos.com/os/docs/1548.0.0/clc-examples.html))

If I have to believe the CoreOS documentation their configuration transpiler actually converts the update configuration to a file (`/etc/coreos/update.conf`), but it would be nice if the provider would add support for it, as the CoreOS documentation says you have to configure these things in YAML, and doesn't specify the config file format.
